ALTER TABLE empresas
  ADD COLUMN IF NOT EXISTS uf VARCHAR(2),
  ADD COLUMN IF NOT EXISTS cep VARCHAR(9),
  ADD COLUMN IF NOT EXISTS cidade VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_empresas_uf ON empresas(uf);
